### ISSUE TITLE
utils.follow_shortlinks for link that expands to https site fails

### ISSUE THREAD

**Issue by cudeso** [edburnett/twitter-text-python#9]
If the shortlink expands to a https site then an SSL error is raised.
Example http://bit.ly/1FEfoab -> https://citizenfourfilm.com/see-the-film

>>> urls=[]
>>> urls.append('http://bit.ly/1FEfoab')       
>>> print utils.follow_shortlinks(urls)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/ttp/utils.py", line 12, in follow_shortlinks
    request_result = requests.get(url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 578, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 178, in resolve_redirects
    allow_redirects=False,
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 385, in send
    raise SSLError(e)

**Comment by stetelepta** [comment]
I ran into a number of SSL related errors with python < 2.7.9 lately. Just tested your snippet with [python 2.7.9](https://www.python.org/downloads/release/python-279/) successfully.
```
Python 2.7.9 (default, Jan  7 2015, 11:49:12) 
>>> import ttp
>>> from ttp import utils
>>> urls=[]
>>> urls.append('http://bit.ly/1FEfoab')
>>> print utils.follow_shortlinks(urls)
{'http://bit.ly/1FEfoab': [u'http://bit.ly/1FEfoab', u'https://citizenfourfilm.com/see-the-film']}
```

**Comment by edburnett** [comment]
This does not appear to be a twitter-text-python error, but rather a problem with SSL certificate verification via the [Requests](http://docs.python-requests.org/en/latest/) module (which ttp.utils depends on) in certain versions of Python.

This should throw the same sort of error:

```python
import requests
requests.get('https://citizenfourfilm.com')
```

While setting certificate verification to false (while not recommended) should work:

```python
requests.get('https://citizenfourfilm.com', verify=False)
```

I verified that this occurs on Debian using Python 2.7.3, however Python 2.7.9 on Archlinux works fine.

Perhaps related to [this Debian bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=766481) with some installations failing to find the root certs?
